#端口
server:
  port: 9292
#数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/jdgl?serverTimezone=GMT%2b8
    username: root
    password: 1234
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    阿里
alipay:
  appId: 
  appPrivateKey: 
  alipayPublicKey:   mybatis-plus:
  mapper-locations: classpath:mapper/*.xml